### ISSUE TITLE
add collection vendimias

### ISSUE THREAD

**Issue by Japoivvb** [RovisRon/DAM2-Viticulture#3]
1. after each vendimia is executed a new document must be saved in a new collection called vendimias with fields
- counter(starting from 1) 
- datetime(showing current date time when vendimia was processed)

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb + details

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by RovisRon** [comment]
![image](https://github.com/RovisRon/DAM2-Viticulture/assets/57545181/84430608-5ee3-4840-9dad-91765e552fb6)

**Comment by Japoivvb** [comment]
working but entity Contador is not used and no required in this design, and name of collection is not the same as requested
